package net.codjo.administration.gui.plugin;

enum ActionType {
    CLOSE,
    GET_PLUGINS,
    START_PLUGIN,
    STOP_PLUGIN,
    GET_LOGS,
    READ_LOG,
    GET_SERVICES,
    ENABLE_SERVICE,
    DISABLE_SERVICE,
    CHANGE_LOG_DIR,
    RESTORE_LOG_DIR,
    CHANGE_JDBC_USERS_FILTER,
    RESTORE_JDBC_USERS_FILTER,
    GET_SYSTEM_PROPERTIES,
    GET_SYSTEM_ENVIRONMENT;
}
